### ISSUE TITLE
rename working branch (optional)

### ISSUE THREAD

**Issue by RedJocker** [BratinaRok/android-bank-manager#12]
it looks a little bit silly your working branch names doesn't it, it is stage1Tests and you are going for stage3 already for what it looks like.

I think you can duplicate it on a branch with better name, delete the old and then push it to github. I don't remenber the code for pushing it, but looking here for  2 minutes I could find this

```
git push origin --delete test-branch
```

**Comment by BratinaRok** [comment]
Ok, I rebased on master branch
