### ISSUE TITLE
checkLogInSuccessful is not testing properly

### ISSUE THREAD

**Issue by RedJocker** [BratinaRok/android-bank-manager#20]
- checkLogInSuccessful is not testing properly
	- one @Test should not depend on other @Test side-effects
		- junit re-instantites all instances for each @Test, but static variables (objects in kotlin) are not re-instantiated
	- Junit does not garantee by default any order of execution of @Test methods
		- your current solution for stage2 uses a static variable "userDataArray" on UserDataSignUp class as repository for user logins that is why checkLogInSuccessful is depending on previous @Test methods
			- it is not good to have mutating state on static variables
			- if there are other mutating state on static variables change that 
	- state is reset, or should be, for every @Test method, so you have to signup first to have a successful login
	- you can reuse newUserSignUp() for login if you take testActivity{} from it

**Comment by BratinaRok** [comment]
Hi, 
What do you suggest to get rid of a static variable in "userDataArray" and refactor code or should I write a method (@Before) to clean static variables after each test? What is a better solution for that?
Thanks
