### ISSUE TITLE
blank fields on sign up

### ISSUE THREAD

**Issue by RedJocker** [BratinaRok/android-bank-manager#4]
you are accepting blank fields for all variables on the sign up page. 
You should be validating those fields to at least not being blank, maybe some other constraints like having a minimal size for password and whatever makes sense.
On EditText there is a .error field you can use to pass error messages, on the particular field that is not valid. I think you should add a requirement for validation with errors being displayed that way and test that requirement

**Comment by BratinaRok** [comment]
Hi, fixed please check
