### ISSUE TITLE
be consistent on naming ids

### ISSUE THREAD

**Issue by RedJocker** [BratinaRok/android-bank-manager#6]
I can see some of your ids are camelCase some are snake_case there is even some allmendedlowercase. pick either the camelCase or the snake_case and do it for all. You can use the renaming feature so that you change only in one place instead of multiple places 

also I can see lots of autogenerated ids like button4, imageView3, I think those should be changed to something descriptive specially if you are requiring their existence.
Maybe you can also prepend the location of the widget on the id like ```singUpUsername``` to make it easier to locate and to avoid conflicting names

**Comment by BratinaRok** [comment]
Hi, fixed please check

**Comment by RedJocker** [comment]
by looking at Stage1UnitTest I can see there still at least one log_in_button while the remaining ids are camelCased

**Comment by RedJocker** [comment]
for what I've seem on the last commits there was progress here, but the views you didn't use yet still have this issue so I'm keeping this one open
