### ISSUE TITLE
screen names on toolbar

### ISSUE THREAD

**Issue by RedJocker** [BratinaRok/android-bank-manager#8]
some of screen names are currently snake_cased like ```sign_up```, ```log_in``` or ```user_logged_in_menu```, that does not look good.

I think those should better be capitalized instead, so it would be ```Sign Up```,   ```Log In```. 

Also ```User Logged In Menu``` is a bad name, maybe ```Main Menu``` is better. Think that this is for an end user eyes not for someone  aware of the inner workings of the code

**Comment by BratinaRok** [comment]
Hi, fixed please check
